config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # add a new route to list the tasks
  get "/tasks/new", to: "tasks#new"
  get "/tasks/:id", to: "tasks#show", as: :task
  get "/tasks", to: "tasks#index"
  # post "/tasks", to: "tasks#create"
  get "/tasks/:id/edit", to: "tasks#edit"
  patch "/tasks/:id/", to: "tasks#update"
  delete "/tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end
end

private

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |task| %>
  <%= task.label :title %>
  <%= task.text_field :title %>
  <%= task.label :details %>
  <%= task.text_field :details %>
  <%= task.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>To do:</h1>
<% @tasks.each do |task| %>
 <ul>
  <li><%= link_to task.title, task_path(task)%></li>
 </ul>
<% end %>

app/views/tasks/new.html.erb
<%# <form action="/tasks" method="post">
  <label for="title">Title</label>
  <input type="text" name="task[title]">
  <label for="description">Description</label>
  <input type="text" name="task[description]">
  <input type="submit">
</form> %>

<%= form_for(@task) do |task| %>
  <%= task.label :title %>
  <%= task.text_field :title %>
  <%= task.label :details %>
  <%= task.text_field :details %>
  <%= task.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<p><%=link_to "Back to all Tasks", tasks_path%></p>